name: workflow overview

on:
  workflow_dispatch: 
  push:
    branches: main

jobs:
  my_self_hosted_job:
    name: my self hosted job
    runs-on: self-hosted
    steps:
      - name: a step in a self hosted runner
        id: selfhostedId
        shell: sh
        run: 
          echo this is a multi lined comment
          echo and this job has been executed from my self-hosted runner
  
      
    
